### ISSUE TITLE
More than two rows having the same peptide sequence and modification for MBR result

### ISSUE THREAD

**Issue by wenbostar** [compomics/moFF#11]
Hi,

I found that there are three rows which have the same peptide sequence and modification as shown below:

![image](https://user-images.githubusercontent.com/5302110/26854676-dbeab528-4adc-11e7-96b8-25141f3ca043.png)

This is the output from MBR module of moFF. Is it normal?

Best regards!
Bo

**Comment by Maux82** [comment]
Hi,
I think that this is issue have been already explained by mail !
