### ISSUE TITLE
moff_mbr breaks output file header

### ISSUE THREAD

**Issue by jgriss** [compomics/moFF#16]
Hi,

I used `moff_mbr` to match features between runs but the output file headers seem to be messed up. Additionally, the value of the `run_test` column was changed from `false` to `0`.

Here's an exmaple (these are simply the first two lines, since the MBR function added PSMs the order was apparently changed):

Original file:
```
peptide prot    mod_peptide     rt      mz      mass    charge  filename        run_test
YLIDHIK P05749;P56628   YLIDHIK 2640.8308       301.1746        900.4997999999999       3.0     mgf/site_86-6A-rep1.mgf false
```

moff-mbr ("_match") file:
```
run_test   charge  code_unique     filename        mass    matched mod_peptide     mz      peptide prot    rt
0.0     2.0     YDSTHGR mgf/site_86-6A-rep1.mgf 834.3547        0       YDSTHGR 418.18533       YDSTHGR P00358;P00359;P00360    1.0525
```

**Comment by Maux82** [comment]
Hi,

Did you run moff_mbr.py alone or have  you run moff_all.py ?

**Comment by jgriss** [comment]
Hi,

I ran moff_mbr.py alone.

Thanks for the help!

**Comment by Maux82** [comment]
moff_mbr.py is supposed to work only inside moff_all.py when you want to run the entire workflow mbr + apex. 
Let me know if you have the same problem when you run moff_all.py

If you are interested in just  the mbr output , just comment lines 140 up to 213 in moff_all.py and it should save the _match files

**Comment by jgriss** [comment]
Thanks for the information! I will give it a try.

Maybe you could update the documentation on the README site. For me, this wasn't apparent.

Thanks for the help!

**Comment by jgriss** [comment]
I have now launched the whole pipeline through `moff_all.py`. Still, the generated *_match.txt files contain messed up headers. The behavior is exactly the same as when calling `moff_mbr.py` directly.

**Comment by Maux82** [comment]
I have tested,  the moff_mbr.py  alone and the header of the gerated file are still fine.

The fact that the order other field is not tha same , it is a behaivuour of pandas  during the concat and merge., but  changhing the values it sounds like a bug.

Can I have a  couple of your input file just to reproduce this problem ?

**Comment by jgriss** [comment]
I have now re-checked all the files: The reason why my scripts broke was not that the order of the columns changed (this is fine) but that a column containing "true" / "false" was changed to "1" / "0".

But I guess this is a pandas thing.

So your code seems to be fine.

Sorry about that!
