### ISSUE TITLE
apex terminated: pandas.parser is deprecated

### ISSUE THREAD

**Issue by lcscs12345** [compomics/moFF#18]
Hi,

Thank you for your platform independent CLI tool. I received the following error when running this command:

`$ python ~/proteomics/src/moFF-1.0/moff.py --tol "10" --inputtsv "test/psm.tsv" --inputraw "test/example.RAW" --output_folder "out"`

`.../moFF-1.0/moff.py:288: FutureWarning: pandas.parser is deprecated and will be removed in a future version.
You can access CParserError as pandas.errors.ParserError
  except pd.parser.CParserError:`

Here are the versions of the dependencies:
pandas: 0.20.3-py27_0
numpy: 1.13.1-py27_0                 
argparse: 1.4.0-py27_0
scikit-learn: 0.19.0-np113py27_0
pymzml: 0.7.8

**Comment by Maux82** [comment]
Hi, 

but does it  stop moFF ? or it is just a warning ?
I will do some test on Pandas 20.3, to see what it is the problem and I will let you know.

Are sure that the input file is a valid tab-delimited file ?

**Comment by lcscs12345** [comment]
I ran more tests and found out that moFF works on the same tsv and RAW files only when they are located in the moFF subdirectory such as sample_data. This error has nothing to do with the version of dependencies.

The following example won't work:
``$ pwd``
``/root/src/moFF/``
``$ ls /root/src/moFF/sample_data/test``
`` 20080315_CPTAC6_07_6A005.RAW 20080315_CPTAC6_07_6A005.txt``
``$ cd /root/src/moFF/sample_data``
``$ python ~/src/moFF/moff.py --tol "10" --inputtsv "test/20080315_CPTAC6_07_6A005.txt" --inputraw "test/20080315_CPTAC6_07_6A005.RAW"``

**Comment by Maux82** [comment]
yes, the input  file path of the should be a  relative from the path where the moFF folder is located.

Maybe I can try to fix it to make it more general. I thought that it was not a big missing but of couse it is also it is not mentioned in the  documentation.
