### ISSUE TITLE
TypeError: compute_peptide_matrix() takes exactly 3 arguments

### ISSUE THREAD

**Issue by caleb-easterly** [compomics/moFF#20]
I got an error when I passed `--peptide_summary` to `moff.py`:

```
Traceback (most recent call last):
  File "moff.py", line 571, in <module>
    main_apex_alone()
  File "moff.py", line 566, in main_apex_alone
    state = compute_peptide_matrix(loc_output,args.tag_pepsum)
TypeError: compute_peptide_matrix() takes exactly 3 arguments (2 given)
```

This is fixed when I pass `log` to compute_peptide_matrix() - that is, when I change

`compute_peptide_matrix(loc_output,args.tag_pepsum)` 

to 
`compute_peptide_matrix(loc_output,log,args.tag_pepsum)`

Thanks!

`

**Comment by Maux82** [comment]
Hi,
I have lost this input during the merge of one of the brances.
Thanks to have  noticed this ! I  have already fixed this in the master brach
