### ISSUE TITLE
Standalone RAW Conversion in Linux

### ISSUE THREAD

**Issue by antortjim** [compomics/moFF#26]
Hi all!

My name is Antonio. I came across this tool forwarded by Marc Vaudel in this google group entry [https://groups.google.com/forum/#!topic/peptide-shaker/Lqe7lYKLcHI](https://groups.google.com/forum/#!topic/peptide-shaker/Lqe7lYKLcHI) (from Peptide Shaker). I think it's great. I am also surprised that you can support the analysis of RAW files as input within a Linux environment, as msconvert from ProteoWizard only supports that in Windows. I can see you make use of an executable called "txic_json.exe", which you call using mono [https://github.com/compomics/moFF/blob/master/moff.py](https://github.com/compomics/moFF/blob/master/moff.py
). 
Would it be possible to extract this conversion functionality as a script by itself, so that RAW files can be converted to mzML or mgf in Linux?

Thank you very much for your help in advance!

Best regards

Antonio

**Comment by Maux82** [comment]
Hi Antonio,

Thanks for using moFF. I hope to release soon  a new version with some intersting filtering option for the matched peaks.

Rearding your question,  I will directly link you to our [Thermo Raw parser ](https://github.com/compomics/ThermoRawFileParser)  a C# program that does the convertion Raw -->  mgf.  The convertion to mzML it should be available soon.  For any question you can contact  @nielshulstaert  he is the developer of our Thermo Raw parser.

**Comment by antortjim** [comment]
Thanks for your answer! I'm sorry it took me a while to get back to you
As you could see, I asked the developer of https://github.com/compomics/ThermoRawFileParser. It seems very promising :) 
Thanks for your time

Best
Antonio
