### ISSUE TITLE
txic

### ISSUE THREAD

**Issue by wolski** [compomics/moFF#3]
Hello,
I am looking for golang sources of txic. 
Thank you.

**Comment by Maux82** [comment]
Hi,
Sorry for my late reply.
The txic is based on the [unthermo ](https://godoc.org/bitbucket.org/proteinspector/ms/unthermo)library.
I can give  you the golang sources of txic, but I m not going to put it on this repository.
if you write me an  [email ](mailto::andrea.argentini@ugent.be) I will send it to you.
