### ISSUE TITLE
moff installation problems

### ISSUE THREAD

**Issue by assafkacen** [compomics/moFF#30]
Hi,
I am trying to install the moff module. the pymzml package support only python ver 3.4 so I convert the moff.py module to run in python 3.X,
It keeps give me errors when I try to work with mzML file. is this the latest version of the code? 
can you tell me what should be the command line to activate the moff on mzML file?

thanks
Assaf

**Comment by bgruening** [comment]
How are you installing moff? Have you tried using bioconda? https://bioconda.github.io/recipes/moff/README.html

**Comment by assafkacen** [comment]
Yes – it  couldn’t find the package in bioconda channel.
I downloaded the package but the code contain many bugs and fail to run – that why I suspect I didn’t download the relevant version.
I can send you a list of bugs if its help..

**Comment by Maux82** [comment]
Hi @assafkacen ,

One way to install it and using  mzML file, is to   install the old version of pymzML that should be  still available. 
Unfortunatly, the new version  of pymzML is only  available  for python 3  but the moving of moFF python 3 is still in our to-do-list.

**Comment by caleb-easterly** [comment]
Hi @assafkacen,

re: moFF in bioconda - it should be there. Did you add bioconda to the list of channels? The instructions are in https://bioconda.github.io/index.html#set-up-channels

Caleb
