### ISSUE TITLE
moFF Beta new version available

### ISSUE THREAD

**Issue by Maux82** [compomics/moFF#31]
Hi @caleb-easterly ,

I have pushed a beta version of moFF that contains the filtering of the matched peaks plus the new CLI as you suggested. 

So far the CLI has been tested only using the loc_in option. I still have some logging issue to solve, but all the new features should work. Can you help  me to test it a bit for me  ?

Now you can use the option --mbr to select the type of workflow and also specify all the options in a configuration file ans use just --config_file 

About the modification, I have just added  two modification files that  work one  for PeptideShaker and one for MQ output.  The modification are just the ones that I usually used in my test dataset. 
The modifications how are specified is a bit tricky,  I hope that you can give some input in order to improve that. 

I will try to update the Readme during the weekend, where all the new parameters will be explained

So far I have just tested this new features only on Themo Raw file, with mzML file I still have to do some test. Moreover, new pymzml  library now only works on python 3 so this makes things a bit more complicated. A  python 3 version of moFF is also on my to do list.

Cheers
Andrea

**Comment by caleb-easterly** [comment]
Hi @Maux82,

Great, thank you! I will test it this week and let you know my thoughts on the new features.

Best,
Caleb

(crossref #29)

**Comment by caleb-easterly** [comment]
Hi @Maux82,

Here's a list of early thoughts. I haven't actually been able to get it to run so far (some dependency issues that I need to iron out), but I'll keep trying. So these are mostly comments designed to make the CLI more intuitive.

1) It's confusing to have all of the different combinations of input parameters (`--loc_in`, `--tsv_list`, `--raw_list`, `--raw_repo`, `--ext`, `--sample`). I think it would be reasonable to just ask people to list all of the files (using wildcards on the command line if necessary), which would drop the number of parameters from 6 to 2. The descriptions could also be clearer - i.e., for `--loc_in`, something like "provide tab-separated peptide-spectrum match file(s)". 
2) `--toll` is misspelled, which could lead to errors. Should be `--tol`
3) For `--w_comb`, `--w_filt`, `--out_flag`, ``--sample_size``, `--peptide_summary`, `--tag_pepsum`, and `--mbr`, `--loc_out`, it would be nice to have the default in the help text.

I'll let you know other comments once I get it running!
