### ISSUE TITLE
number of cores need to be adjustable

### ISSUE THREAD

**Issue by bgruening** [compomics/moFF#33]
https://github.com/compomics/moFF/blob/master/moff.py#L376 should be adjustable by an admin. Otherwise, this tool will be always killed by a scheduler on a cluster.

**Comment by Maux82** [comment]
How can I make it  adjustable by an admin ?   Do you think is it better to  add the number of CPU as input parameter (as default I set it to multiprocessing.cpu_count() ) ?

**Comment by bgruening** [comment]
Yes, a parameter that is overwriting your default would be nice. Thanks!
