### ISSUE TITLE
local variable 'xic_data' referenced before assignment

### ISSUE THREAD

**Issue by Cheng111** [compomics/moFF#39]
Hi, when I try to run the moff on Ubuntu, there is a error report "local variable 'xic_data' referenced before assignment". It looks like that something wrong with the get_xic_data function. Is there anything I didn't wrong. Thank you so much.

The command I used is "python3 ./moff_all.py  --mbr off --tsv_list moff_input.tsv --raw_list *.mzML --rt_peak_win 0.75 --tol 10 --loc_out ./moff/ --xic_length 3"

I attached part of the error report here. It's same error appear several times.
Traceback (most recent call last):
  File "/usr/lib/python3.5/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/home/cades/tools/moFF/moff.py", line 838, in apex_multithr
    raise e
  File "/home/cades/tools/moFF/moff.py", line 829, in apex_multithr
    flag_mzml, flag_windows, temp, loc_output, name_file, txic_path, loc, 0)
  File "/home/cades/tools/moFF/moff.py", line 1005, in get_xic_data
    return xic_data
UnboundLocalError: local variable 'xic_data' referenced before assignment
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "./moff_all.py", line 416, in <module>
    result = moff.save_moff_apex_result(result)
  File "/home/cades/tools/moFF/moff.py", line 144, in save_moff_apex_result
    raise e
  File "/home/cades/tools/moFF/moff.py", line 133, in save_moff_apex_result
    if result[df_index].get()[1] == -1:
  File "/usr/lib/python3.5/multiprocessing/pool.py", line 608, in get
    raise self._value
UnboundLocalError: local variable 'xic_data' referenced before assignment

**Comment by Maux82** [comment]
Hi ,

Thanks for reporting this. I am aware of this bug.
Actually , I am still fixing the access to the mzML file in this new version. I hope to solve this for the end of the next week. In the meantine you can use moFFwith Thermo raw file.

**Comment by subinamehta** [comment]
Hi ,
I am also finding this issue using moFF...could you please let me know when this is fixed!! 
Thanks,
Subina

**Comment by Maux82** [comment]
Hi @subinamehta ,

The last version  in the master branch should work with mzML.  Let me know if you if you get the same error .

**Comment by Maux82** [comment]
Hi, @Cheng111  
now moFF should work with mzML , let me know if you find other issue with mzML.

**Comment by subinamehta** [comment]
I still get the same error..so I did conda update moff and then ran this "python moff_all.py --mbr off --tsv_list jrudney_chenx096_20141205_14469_737NS_08_23.tabular --raw_list jrudney_chenx096_20141205_14469_737NS_08_23.mzml --tol 10 --loc_out output_moFF1" and it gives me the error 
"UnboundLocalError: local variable 'xic_data' referenced before assignment"

**Comment by Maux82** [comment]
@subinamehta  ARe you sure that you are using  the  last version from the master branch ?  you can try to pull it down again?  I tried your command  and for me it  work.

**Comment by subinamehta** [comment]
Let me give it a try once more

**Comment by Maux82** [comment]
@subinamehta here is my  last commit  (in moff.py )where I fixed the mzml part  https://github.com/compomics/moFF/commit/3e9b9b22a4f79052c5c284a6da9fbda9fd597674.

**Comment by subinamehta** [comment]
@Maux82 so I have sent u few files regarding the error I have been getting!

**Comment by subinamehta** [comment]
Could you check the bioconda version of moFF???
