### ISSUE TITLE
Basic question about the quantitation algorithm

### ISSUE THREAD

**Issue by Stortebecker** [compomics/moFF#4]
Hi!
I would like to ask about the background of the MoFF quantitation algorithms as I could not find a publication explaining it. The MS1 quantitation algorithms I knew so far (i.e. XPRESS, ASAPRatio, FeatureFinder in OpenMS) were all based on integration of the whole area of a MS1 peak. If I get it right, MoFF works instead solely with the highest value (= the apex) of a peak. 
Is this commonly used for peak quantitation? How does this approach compare to the mentioned algorithms?

**Comment by Maux82** [comment]
Hi,
yes you had the right intuition. 
moFF gets only the apex of each annotated feature given in input. For each feature (rt,mz,charge,mass) moFF extracts the XiC just using the monoisotopic mass of the peptides.
 In a paper that will be available soon in Nature Methods, we compare moFF and MAxQuant intensities showing really high correlation coefficient. Also from the quantitative perspective for the match-between-run, moFF finds matched features as much as MaxQuant does. As soon the paper will be online I will update the readme information.

**Comment by Stortebecker** [comment]
Cool, I am eagerly waiting for some tutorial for the match-between-runs-part of MoFF! I cannot use MQ and this seems to be very powerful.
