### ISSUE TITLE
Raw to mgf conversion in moFF?

### ISSUE THREAD

**Issue by CarlosHorro** [compomics/moFF#46]
Hi,

I just wanted to ask if, at some point, it is planned to include the conversion from Raw to MGF in moFF (as it's already using the RawFileReader).

Greetings,
Carlos

**Comment by Maux82** [comment]
hi,
I suppose you mean the conversion between raw to mzml because the mgf format is not used in moff.
there is no plan to include the conversion from raw to mzml.

**Comment by CarlosHorro** [comment]
Um... well, I though moFF is prepared for running in a unique workflow together with PeptideShaker, I've already seen that moFF accepts PS's PSM report, but PS still needs mgfs files (it cannot manage directly raw files). So, in order to run them both together, do you use an external conversion tool to get mgfs files and give them to PeptideShaker?

**Comment by bgruening** [comment]
@CarlosHorro can you not use: https://usegalaxy.eu/root?tool_id=toolshed.g2.bx.psu.edu/repos/galaxyp/thermo_raw_file_converter/thermo_raw_file_converter/0.0.1 ?

**Comment by CarlosHorro** [comment]
> @CarlosHorro can you not use: https://usegalaxy.eu/root?tool_id=toolshed.g2.bx.psu.edu/repos/galaxyp/thermo_raw_file_converter/thermo_raw_file_converter/0.0.1 ?

Well, maybe, I have not tried that tool yet (although it still seems to be in beta version), we just wondered about how moFF managed this scenario...

**Comment by Maux82** [comment]
@CarlosHorro in this scenario , moFF works fine because does not need any mgf file in input. if you integrate Thermo_raw_file_converter  in PS-searchgui  and then you run moFF on PS report (PSM report) and its original raw file/mzml  works.

**Comment by CarlosHorro** [comment]
Thank you for the info :-)
