### ISSUE TITLE
Quantitation of Peptides and Proteins

### ISSUE THREAD

**Issue by Stortebecker** [compomics/moFF#5]
Do you have recommendations on how to map MoFF PSM quantitations on peptides and finally on proteins?

**Comment by Maux82** [comment]
Hi,
moFF has been designed just to extract the MS1 intensities, but its output can be easily integrated in other statistical sw such as Perseus or R.

At the moment I do not have any specific recommendation, but in the next future we are planning to integrate moFF output into [this ](http://www.mcponline.org/content/15/2/657.short) novel peptide-based quantification approach

**Comment by Stortebecker** [comment]
> At the moment I do not have any specific recommendation, but in the next future we are planning to integrate moFF output into this novel peptide-based quantification approach

Sounds great! Is the approach you cited already available as a software? I could not find it.

**Comment by Maux82** [comment]
Here we go : https://github.com/ludgergoeminne/MSqRob
if you have questions you can contact the [author](mailto:Ludger.Goeminne@UGent.be)
