### ISSUE TITLE
What is txic?

### ISSUE THREAD

**Issue by fcyu** [compomics/moFF#7]
Can you provide the source code or algorithm of txic?

Thanks

**Comment by Maux82** [comment]
The txic is a golang program based on the unthermo library. txic retrived the XiC data for each fetures in input.
I can give you the golang sources of txic, but I m not going to put it on this repository.
if you write me an email I will send it to you.

**Comment by fcyu** [comment]
Thanks for your reply. Your explanation is clear enough. I think the source code is not necessary if it is just a data reading module.

Thanks
