### ISSUE TITLE
Could moFF output the retention time boundary of the integrated ion intensity envelop

### ISSUE THREAD

**Issue by fcyu** [compomics/moFF#9]
I know that moFF output "lwhm" and "rwhm". However, they are not the boundary. Could moFF output the boundary for us to plot the curve easily?

Thanks

**Comment by Maux82** [comment]
Hi, 

Can you explain me with more details the time boundary that you need ?
In principle you can  get the entire XiC inside the intervall rt +/- rt_w.

**Comment by fcyu** [comment]
Hi,

Thanks for your reply. I would like to illustrate it with a figure:

![681689538615036753](https://cloud.githubusercontent.com/assets/6926299/21535201/bd55ac2e-cdac-11e6-8903-ddb913ab5654.jpg)

I marked the left boundary and right boundary with red color. It is clear that only the intensities within this range should be integrated. moFF reports LWHM and RWHM which are narrower than left boundary and right boundary. Thus, I wonder if moFF could report two boundaries?

Thanks

**Comment by Maux82** [comment]
Hi ,

Sorry for my late reply but I was on holiday.
Yes of course, it is possible to detect the rt boundary of the peak but to do that you need to consider the peak intensities as peak area considering the isotopic envelope of the possible peptides.  This is  the opposite of  the apex  approach  of moFF that aims to keep away the computatioanl burden of the  intensities integration. 

At the moment this  feature is not the list of the next moFF improvements, but of course you are really welcome to implement it by your own starting from the moFF code.

**Comment by fcyu** [comment]
Hi,

Thanks for your reply.

Now, I am confused. I recheck your paper, there is no details about how to get the total ion intensity after obtaining the apex. Could you please briefly describe the algorithm since it is not based on the intensities integration?

Thanks

**Comment by Maux82** [comment]
moFF, for every features  both for machted or ms2 identified, extracts the apex intensitiy in the XiC related to the monoisotopic mass  of the feature (using the rt_w, and the rt_p windows).  In moFF there is no any kind of intensities  integration, it provides only apex intensities. 

[Here](http://www.nature.com/nmeth/journal/v13/n12/fig_tab/nmeth.4075_SF2.html), you can find a slide that explains how the apex is extracted  and how the quality metrics are computed.

**Comment by fcyu** [comment]
Thanks for your clearly reply.
